### ISSUE TITLE
icons are not loaded correctly and file manipulation will report an error

### ISSUE THREAD

**Issue by LesanOuO** [fernandoescolar/vscode-solution-explorer#216] opened 2022-08-31 03:46 UTC
**Describe the bug**
1. icons cannot be loaded properly in windows environment.
![image](https://user-images.githubusercontent.com/51104338/187587804-8f429274-f79b-4e86-823a-aa6755e93697.png)

2. When doing file operation, there will be many error output, but the operation is executed normally.
For example, when I delete a file, the file can be deleted normally, but OUTPUT prints error
![image](https://user-images.githubusercontent.com/51104338/187587740-d445d872-5070-4165-a191-9b5c210b141a.png)

In my opinion ：
I think it's caused by vscode.workspace.fs

**Comment by fernandoescolar** [comment] 2022-08-31 06:18
I can't reproduce it on an Apple silicon. Maybe it only happens on Windows. Anyway, if this problem is related to a bug in the vscode library, maybe we should leave the code as is and open an issue in the vscode project… or do you think it would be better to put the option to use `fs` or `vscode.workspace.fs` in the configuration?

**Comment by wladslaw** [comment] 2022-09-02 06:38
@fernandoescolar
It isn't related to Windows. I also have the same issue with the icons on my Ubuntu 22.04  

VSCode info:
```
Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:10.472Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-47-generic
Sandboxed: No
```

**Comment by fernandoescolar** [comment] 2022-09-02 07:59
I just found it. It was a problem related to asynchronous methods. It is now fixed and this fix will be published in the next version :)

**Closed** 2022-09-05 10:12 UTC
Labels: bug
